sonar.projectKey=NTT-Product-Incubator_ProductIncubator-Loopy
sonar.organization=ntt-product-incubator

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=ProductIncubator-Loopy
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclude duplication for files where duplication isn't a concern
sonar.cpd.exclusions=**/*.html

# Ignored issues for SonarCloud scanning
sonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5,e6,e7,e8,e9

# Ignore issues related to the use of var, as it's necessary for requires and unit tests
sonar.issue.ignore.multicriteria.e1.ruleKey=javascript:S3504
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.js
# Ignore issues related to the use of boolean literals, since this has some benefit in how verbose it is
sonar.issue.ignore.multicriteria.e2.ruleKey=javascript:S1125
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.js
# Ignore issues related to the default use of sort to sort alphabetically, since this is often the actual use case
sonar.issue.ignore.multicriteria.e3.ruleKey=javascript:S2871
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.js
# Ignore issues related to moving declarations that are used in unit tests
sonar.issue.ignore.multicriteria.e4.ruleKey=javascript:S2392
sonar.issue.ignore.multicriteria.e4.resourceKey=**/*.js
# Ignore code smell issues related to function complexity for now
sonar.issue.ignore.multicriteria.e5.ruleKey=javascript:S3776
sonar.issue.ignore.multicriteria.e5.resourceKey=**/*.js
# Ignore resource integrity checks for included JS for now; plan is to review them properly before including
sonar.issue.ignore.multicriteria.e6.ruleKey=Web:S5725
sonar.issue.ignore.multicriteria.e6.resourceKey=**/*.html
# Stop complaining about Object.assign. We know you like the spread operator more, but both are valid.
sonar.issue.ignore.multicriteria.e7.ruleKey=javascript:S6661
sonar.issue.ignore.multicriteria.e7.resourceKey=**/*.js
# String.charAt is fine when used properly. startsWith/endsWith isn't a necessary optimization.
sonar.issue.ignore.multicriteria.e8.ruleKey=javascript:S6557
sonar.issue.ignore.multicriteria.e8.resourceKey=**/*.js
# Ignore deprecation warnings for now, revisit once we switch to https
sonar.issue.ignore.multicriteria.e9.ruleKey=javascript:S1874
sonar.issue.ignore.multicriteria.e9.resourceKey=**/*.js
