/** *************************************************************************************************
User Summary
This code controls the functionality of a node. It allows users to send and receive signals to other
nodes via connected arrows, functionality for the look of the node, and functionality for a node to
be killed or revived.

Technical Summary:
The Node class is used for creating and managing nodes in a Loopy model. The nodes can send and receive signals to other nodes via connected arrows. 

The Node class defines various static properties related to the nodes, such as COLORS (an object mapping node colors), signalColor (the color of signals), 
DEFAULT_RADIUS (the default radius of a node), and _CLASS_ (the class name).

The Node constructor function initializes a node with a reference to the Whiteboard object, a configuration object, and default values for various properties. 
These properties include wip (work in progress), overCapacity (a queue for signals waiting to be processed when the node is full), 
nodeSentTo (an array of nodes this node has sent signals to), timeouts (an array of timeout IDs), 
edgeToSend (the edge to send the next signal to), ratios (an array of ratios for sending signals to connected nodes), 
maxLabelLength (the maximum length of the node label), workItemsCompleted (the number of work items completed by this node), 
workItemsSelfGenerated (the number of work items self-generated by this node), and several other properties related to the node's statistics and state.

The Node class defines various methods for sending and receiving signals, processing signals, creating new signals, populating the nodeSentTo array,
loadBalancePopulate (populating the load balancing array), returnRatioPopulate (populating the return ratio array), takeSignal (receiving a signal from another node),
processSignal (processing a received signal), update (updating the node's state), draw (drawing the node on the canvas), drawLabel (drawing the node label on the canvas),
drawBottleneck (drawing the bottleneck status indicator on the canvas), drawFloatDisplay (drawing a floating display for the node's statistics), and kill (removing the node from the whiteboard).

************************************************************************************************** */

// Define colors for nodes
Node.COLORS = {
    0: '#EA3E3E', // red
    1: '#EA9D51', // orange
    2: '#FEEE43', // yellow
    3: '#BFEE3F', // green
    4: '#7FD4FF', // blue
    5: '#A97FFF', // purple
    7: 'rgba(0,0,0,.3)', // node settings
};

Node.signalColor = '#666666';

// Setting default values
Node.DEFAULT_RADIUS = 60;
Node._CLASS_ = 'Node';

// Load balance highlight when selecting input
const LOAD_BALANCE_HIGHLIGHT = 'rgba(125, 115, 120, 0.4)';
const MAX_LINES = 6;

// Node class
function Node(whiteboard, config) {
    const self = this;
    self._CLASS_ = 'Node';
    self.wip = 0; // number of units in progress
    self.overCapacity = []; // if node is full (wip reaches size), queue holds signals waiting to be processed
    self.nodeSentTo = [];
    self.timeouts = [];
    self.edgeToSend = 0;
    self.ratioCounter = 0;
    self.nodeRatioIsSelected = false;
    self.nodeRatioHighlight = "";
    self.ratios = [];
    self.maxLabelLength = 20;
    self.wasPaused = false;
    self.workItemsCompleted = 0;
    self.workItemsSelfGenerated = 0;
    
    self.created = Date.now();

    // Idle Time
    self.idleTime = 0;
    self.idleTimeDisplay = 0;

    // Calculated stats
    self.timeInQueue = 0; // Queue / Capacity * Processing Time
    self.queueExceeds = 0; // In Queue / Capacity
    self.avgTimeInQueue = 0; // Sum of all work item’s time spent in ‘In Queue’ / total # of work items (include items that bypassed ‘In Queue’, for the ones bypassed the time spent would be 0)
    self.utilizationRate = 0; // (Total usable bandwidth (capacity * time elapsed in the simulation) - idle time (total un-used capacity throughout time elapsed in the simulation)) / total usable bandwidth
    self.bottleneckPercentage = 0; // Total time the node is flagged as any shade of red / total time elapsed
    self.totalNumOfWorkItems = 0;
    self.workItemQueueTime = 0;
    self.bottleneckTime = 0;
    self.bottleneckRed = false;
    self.daysElapsedNode = 0;


    // Mah Parents!
    self.loopy = whiteboard.loopy;
    self.whiteboard = whiteboard;
    self.config = config;

    // Default values...
    const defaultProperties = {
        radius: Node.DEFAULT_RADIUS,
    };
    setStoredPropertyDefaults(defaultProperties, Node);
    _configureProperties(self, config, defaultProperties);
    // Value: from 0 to 1
    self.initFillRate = function () {
        let initalCount = Math.round((self.init / 100) * self.size)
        self.value = initalCount / ((self.size >= 1)? self.size : 1); // value handles visual fill of node
    };
    self.initFillRate();

    // Determine if the node is read-only
    function readOnlyRules() {
        return self.loopy.mode !== Loopy.MODE_PLAY;
    }

    // MOUSE.
    let _controlsVisible = false;
    let _controlsAlpha = 0;
    let _controlsDirection = 0;
    let _controlsSelected = false;
    let _controlsPressed = false;
    const _listenerMouseMove = subscribe('mousemove', () => {
        if (readOnlyRules()) return;

        // If moused over this, show it, or not.
        _controlsSelected = self.isPointInNode(Mouse.x, Mouse.y);
        if (_controlsSelected) {
            _controlsVisible = true;
            self.loopy.showPlayTutorial = false;
            _controlsDirection = 1;
        } else {
            _controlsVisible = false;
            _controlsDirection = 0;
        }
    });

    self.setInspectVals = function(id, text) {
        document.getElementById(id).innerHTML = text;
    };

    self.setTitle = function(id, text) {
        let elem = document.getElementById(id);
        elem.setAttribute('data-bs-original-title', text);
    };



    // Mouse event handlers
    const _listenerMouseDown = subscribe('mousedown', () => {
        for (let node of loopy.whiteboard.nodes) {
            if (node.id == self.id && node.created != self.created) {
                return; 
            }
        }

        if (readOnlyRules()) return;
        if (_controlsSelected && !loopy.pause) _controlsPressed = true;

        // IF YOU CLICKED ME... AND this arrow is active
        if (_controlsPressed && _controlsDirection && !loopy.pause) {
            // Change my value
                const delta = _controlsDirection;
                self.takeSignal({
                    delta,
                    color: Node.signalColor,
                });
            
        } 
        // Node Inspect Menu
        else if(loopy.pause && _controlsSelected) {
            document.getElementById('odometerNeedleImage').style.animation = 'none';

            loopy.sidebar.showPage('Inspect');
            document.body.classList.remove('sidebar-closed');
            document.body.classList.add('sidebar-open');
            sidebarSwitch.style.display = 'block';
            let vsn = document.getElementById('valueStreamName');
            vsn.classList.add('nodeInspectOpen');
            publish('resize');
            self.setInspectVals('inspectName', self.label);
            self.setInspectVals('inspectWIP', self.wip);
            self.setInspectVals('inspectInQueue', self.overCapacity.length);
            self.setInspectVals('inspectCapacity', self.size);
            const inspectDays = (self.aggregationLatency == 1) ? 'day' : 'days';
            self.setInspectVals('inspectProcessingTime', `${self.aggregationLatency} ${inspectDays}`);
            for(let i = 0; i < 10; i++){
                hide(`inspectReturnRatioMultiNode${i}`);
                self.setTitle(`returnRatioTooltip${i}`, '');
                self.setTitle(`returnRatioTooltipSingleNode`, '');
            }
            hide('returnRatioTooltipDiv1');
            hide('returnRatioTooltipDiv2');
            hide('inspectReturnRatioMultiNodeLabel');
            hide('inspectReturnRatioSingleNodeLabel');
            hide('inspectReturnRatioSingleNode');
            if (self.edgeToReturn.length == 1){
                show('inspectReturnRatioSingleNode', 'flex');
                show('inspectReturnRatioSingleNodeLabel', 'flex');
                self.setInspectVals('inspectReturnRatioSingleNode', `${self.edgeToReturn[0].returnRatioPercent}% `);
                self.setTitle(`returnRatioTooltipSingleNode`, `${self.edgeToReturn[0].label}`);
            } else if (self.edgeToReturn.length > 1) {
                show('inspectReturnRatioMultiNodeLabel', 'block')
                show('returnRatioTooltipDiv1');
                if (self.edgeToReturn.length > 5) {
                    show('returnRatioTooltipDiv2');
                }
                
                for(let returnRatioIndex in self.edgeToReturn) {

                    show(`inspectReturnRatioMultiNode${returnRatioIndex}`, 'inline');
                    self.setInspectVals(`inspectReturnRatioMultiNode${returnRatioIndex}`, `${self.edgeToReturn[returnRatioIndex].returnRatioPercent}% `);
                    self.setTitle(`returnRatioTooltip${returnRatioIndex}`, `${self.edgeToReturn[returnRatioIndex].label}`);
                }

                
            }

            document.getElementById('odometerNeedleImage').style.animation = `${self.bottleneckColor} 3s forwards`;

            // call function to calculate stats
            self.calculatedStats();

            // calculated stats
            const queueTimeDays = (self.timeInQueue == 1) ? 'day' : 'days';
            self.setInspectVals('timeInQueue', `${self.timeInQueue} ${queueTimeDays}`);
            self.setInspectVals('queueExceeds', `${self.queueExceeds} times`);
            const avgTimeInQueueDays = (self.avgTimeInQueue == 1) ? 'day' : 'days';
            self.setInspectVals('avgTimeInQueue', `${self.avgTimeInQueue} ${avgTimeInQueueDays}`);
            self.setInspectVals('utilizationRate', `${self.utilizationRate} %`);
            self.setInspectVals('bottleneckPercentage', `${self.bottleneckPercentage} %`);
            
            // Counted stats
            self.setInspectVals('workItemsCompleted', self.workItemsCompleted);

            // Hide stats by default
            hide('lineCountedProperty');
            for(let i=0; i<10;i++) {
                hide('workAllocationTitle');
                hide(`inspectCountedProperty${i}`);
                hide(`workItemsSent${i}`);
            }
            // show if there is node
            if(self.nodeSentTo.length > 1) {
                show('lineCountedProperty');
                for(let index in self.nodeSentTo) {
                    show('workAllocationTitle', 'flex');
                    show(`inspectCountedProperty${index}`, 'flex');
                    show(`workItemsSent${index}`, 'flex');
                    self.setInspectVals(`inspectCountedProperty${index}`, `${self.nodeSentTo[index].label}:`);
                    self.setInspectVals(`workItemsSent${index}`, `${self.nodeSentTo[index].count}`);
                }
            }

        }
    });

    self.calculatedStats = function () {
        // timeInQueue
        self.timeInQueue = (Math.ceil(self.overCapacity.length / self.size) * self.aggregationLatency);

        // queueExceeds
        self.queueExceeds = (self.overCapacity.length / self.size).toFixed(2).replace(/[.,]00$/, "");

        //avgTimeInQueue
        if (self.totalNumOfWorkItems == 0) {
            self.avgTimeInQueue = 0;
        }
        else {
            self.avgTimeInQueue = (self.workItemQueueTime / self.totalNumOfWorkItems).toFixed(2);
        }
        if (self.daysElapsedNode == 0) {
            self.utilizationRate = 0;
            self.bottleneckPercentage = 0;
        }
        else {
            let realIdleTime = self.idleTime;
            // utilizationRate
            if((self.size * self.daysElapsedNode) < self.idleTime) {
                realIdleTime = self.size * self.daysElapsedNode;
            }
            self.utilizationRate = Math.round((((self.size * self.daysElapsedNode) - realIdleTime) / (self.size * self.daysElapsedNode)) * 100);
            // bottleneckPercentage
            self.bottleneckPercentage = Math.round((self.bottleneckTime / self.daysElapsedNode) * 100);
        }

    };
    
    // Stops taking input when mouse is released
    const _listenerMouseUp = subscribe('mouseup', () => {
        if (readOnlyRules()) return;
        _controlsPressed = false;
    });
    // resets whiteboard
    const _listenerReset = subscribe('whiteboard/reset', () => {
        self.value = self.init / 100;
        self.overCapacity = [];
        self.edgeToSend = 0;
        self.nodeRatioIsSelected = false;
        self.nodeRatioHighlight = "";
        self.nodeSentTo = [];

        // Idle Time reset
        clearInterval(self.idleInterval);
        self.idleInterval = null;
        self.idleTime = 0;

        // Idle Time reset
        clearInterval(self.inQueueInterval);
        self.inQueueInterval = null;
        self.workItemQueueTime = 0;
        self.totalNumOfWorkItems = 0;

        clearInterval(self.bottleneckInterval);
        self.bottleneckInterval = null;
        self.bottleneckTime = 0;
        self.bottleneckRed = false;
        
        clearInterval(self.daysElapsedNodeInterval);
        self.daysElapsedNodeInterval = null;
        self.daysElapsedNode = 0;
        
        self.wasPaused = false;
        self.wip = 0;
        self.workItemsCompleted = 0;

        // Resets number of self generated work items
        self.workItemsSelfGenerated = 0;
    });

    /// ///////////////////////////////////
    // SIGNALS ///////////////////////////
    /// ///////////////////////////////////


    // Creates a new signal with values of old signal
    // Causes issues when you try to send the same signal
    self.createNewSignal = function(signal, type) {
        const newSignal = {
            delta: signal.delta,
            age: self.lastSignalAge,
            color: Node.signalColor,
        };
        return newSignal;
    }
    //populate nodeSendTo
    self.nodeSentToPopulate = function() {
        self.nodeSentTo = [];
        const edgesToPopulate = self.whiteboard.getEdgesByStartNode(self);
        for(const edge of edgesToPopulate) {
            self.nodeSentTo.push({'label': edge.to.label, count: 0});
        }
    }


    // populate the load balancing array
    self.loadBalancePopulate = function () {
        self.edgeToSend = 0;
        self.ratioCounter = 0;
        const edgesToPopulate = self.whiteboard.getEdgesByStartNode(self);
        self.ratios = [];
        for (let i = 0; i < edgesToPopulate.length; i++) {
            self.ratios.push(self["loadBalancingInput"+i]);
        }
    };

    // populate the return ratio array
    self.returnRatioPopulate = function () {
        self.edgeToReturn = [];
        let endNodeEdges = self.whiteboard.getEdgesByEndNode(self);

        for (let i = 0; i < endNodeEdges.length; i++) {
            let input = self["returnRatioInput"+i];

            let gcd = self.gcd(input, 100);
            let denominator = 100 / gcd;
            let numerator = input / gcd;

            self.edgeToReturn.push({'numerator':numerator, 'denominator':denominator, count: 0, 'returnRatioPercent': input, 'label': endNodeEdges[i].from.label});
        }
    };

    self.gcd = function (numerator, denominator) { 
        if (denominator == 0) {
            return numerator;
        }
        return self.gcd(denominator, numerator % denominator);
   };


    // Send a signal from this node to the connected nodes
    self.sendSignal = function (signal) {
        // Decrement wip and decrease value of node
        self.wip--;
        self.workItemsCompleted++;
        self.value -= signal.delta / self.size;
        if(self.overCapacity.length > 0) {
            self.takeSignal(self.overCapacity.shift());
        }
        // do nothing if node is single
        const myEdges = self.whiteboard.getEdgesByStartNode(self);

        if(myEdges.length > 0) {
            // Edge to send too
            let edge;
            // check to see if we sent the number of signals equal that edge's ratio, if so reset counter and move to next edge
            if(self.ratioCounter >= self.ratios[self.edgeToSend]) {
                if (self.edgeToSend + 1 >= self.ratios.length) { 
                    self.edgeToSend = 0;
                } else {
                    self.edgeToSend++;
                }
                self.ratioCounter = 0;    
            }

            edge = myEdges[self.edgeToSend];
            self.ratioCounter++;
            self.nodeSentTo[self.edgeToSend].count++;

            edge.addSignal(self.createNewSignal(signal));
            edge.to.takeSignal(self.createNewSignal(signal), edge.from);

        }

        if (self.value < 0) self.value = 0;
        if (self.value > 1) self.value = 1;
    };


    self.signalProcessOrQueue = function(signal) {
        // increase total number of work items
        self.totalNumOfWorkItems++;
        
        // If the node is full, add signal to queue
        if(self.wip >= self.size) {
            self.overCapacity.push(self.createNewSignal(signal));
            return;
        }
        // increment work in progress and node value 
        self.value += signal.delta / self.size;
        if (self.value < 0) self.value = 0;
        if (self.value > 1) self.value = 1;

        // Animation
        if (signal.delta > 0) _offsetVel -= 6;
        if (signal.delta < 0) _offsetVel += 6;

        self.processSignal(signal);
    }

    // Receives a signal from another node
    self.takeSignal = function (signal, node) {
        
        let returnRatioIndex = -1;
        let returnRatioEdge;
        if(node){
            for(let edge in self.whiteboard.getEdgesByEndNode(self)) {
                if(self.whiteboard.getEdgesByEndNode(self)[edge].from.id == node.id){
                    returnRatioIndex = edge;
                    returnRatioEdge = self.whiteboard.getEdgesByEndNode(self)[edge];
                    break;
                }
            }
        }
        
        if (node && returnRatioEdge && returnRatioIndex != -1) {
            self.edgeToReturn[returnRatioIndex].count++;
            let returnRatio = self.edgeToReturn[returnRatioIndex];
            if (returnRatio.count > returnRatio.denominator) {
                returnRatio.count = 1;
            } 
            if (returnRatio.count > returnRatio.denominator - returnRatio.numerator || returnRatio.denominator - returnRatio.numerator == 0) {
                returnRatioEdge.addReverseSignal(self.createNewSignal(signal));
                node.takeSignal(self.createNewSignal(signal));
                return;
            }
        }

        self.signalProcessOrQueue(signal);
    };

    // Prepares signal to be sent
    self.processSignal = function(signal) {
        self.wip++;
        // Update age
        self.lastSignalAge = signal.age;

        // sending function
        const send = () => {
            if (self.loopy.mode === Loopy.MODE_PLAY) {
                self.sendSignal(self.createNewSignal(signal));
            }
        };

        // Inverse of signalSpeed
        // As speed gets faster, need a slower timeout
        const signalSpeedRatio = 8 / 2 ** self.loopy.signalSpeed;

        // Handling latency
        if(self.loopy.mode == Loopy.MODE_PLAY){
            const timeout = new Timeout(send, 1000 * self.aggregationLatency * signalSpeedRatio);
            if(this.loopy.pause) {
                timeout.pause();
            }

            self.timeouts.push(timeout);
        }
    };


    self.selfGenerate = function() {
        const signal = {
            delta: 1,
            color: Node.signalColor,

        };

        // generate signals
        if (self.loopy.mode === Loopy.MODE_PLAY) {
            for(let i=0; i<self.generateVolume; i++) {
                self.signalProcessOrQueue(signal);
                self.workItemsSelfGenerated += 1;
                // stop generated if reached max
                if(self.generateMax && self.generateMax <= self.workItemsSelfGenerated) {
                    return;
                }

            }
            

            //repeated self generation
            const signalSpeedRatio = 8 / 2 ** self.loopy.signalSpeed;
            const timeout = new Timeout(self.selfGenerate, 1000 * self.generateInterval * signalSpeedRatio);
            if(this.loopy.pause) {
                timeout.pause();
            }

            self.timeouts.push(timeout);
        }
    };
    /// ///////////////////////////////////
    // UPDATE & DRAW /////////////////////
    /// ///////////////////////////////////

    self.breakText = function () {
        const lines = self.label.split(/\n/);
        if (self.href) lines[0] = `🔗 ${lines[0]}`;
        return lines;
    };


    // Update!
    let _offset = 0;
    let _offsetGoto = 0;
    let _offsetVel = 0;
    let _offsetAcc = 0;
    const _offsetDamp = 0.3;
    const _offsetHookes = 0.8;
    self.update = function () { // (speed)
        // When actually playing the simulation...
        const _isPlaying = (self.loopy.mode === Loopy.MODE_PLAY);

        // calculates the idle time
        if (_isPlaying) {

            let interval = 250;
            // calculates the idle time
            if (!self.idleInterval) {
                self.idleInterval = setInterval(function () {
                    if (self.size == self.wip || loopy.pause) return;
                    self.idleTime += ((self.size - self.wip) * (interval / 1000)) * ((2 ** loopy.signalSpeed) / 8);
                }, interval);
            }

            // variable used for displaying the idle time, rounded to whole seconds (days)
            self.idleTimeDisplay = Math.round(self.idleTime);

            if (!self.inQueueInterval) {
                self.inQueueInterval = setInterval(function () {
                    if (self.overCapacity < 0 || loopy.pause) return;
                    self.workItemQueueTime += ((self.overCapacity.length) * (interval / 1000)) * ((2 ** loopy.signalSpeed) / 8);
                }, interval);
            }

            if (!self.bottleneckInterval) {
                self.bottleneckInterval = setInterval(function () {
                    if (!self.bottleneckRed || loopy.pause) return;
                    self.bottleneckTime += (interval / 1000) * ((2 ** loopy.signalSpeed) / 8);
                }, interval);
            }

            if (!self.daysElapsedNodeInterval) {
                self.daysElapsedNodeInterval = setInterval(function () {
                    if (loopy.pause) return;
                    self.daysElapsedNode += (interval / 1000) * ((2 ** loopy.signalSpeed) / 8);
                }, interval);
            }
        }

        // Otherwise, value = initValue exactly
        if (self.loopy.mode === Loopy.MODE_EDIT) {
            self.initFillRate();
        }

        // Cursor!
        if (_controlsSelected && _controlsDirection && !readOnlyRules()) Mouse.showCursor('pointer');

        // Visually & vertically bump the node
        const gotoAlpha = (_controlsVisible || self.loopy.showPlayTutorial) ? 1 : 0;
        _controlsAlpha = _controlsAlpha * 0.5 + gotoAlpha * 0.5;
        if (_isPlaying && _controlsPressed) {
            _offsetGoto = -_controlsDirection * 20; // by 20 pixels
            // _offsetGoto = _controlsDirection*0.2; // by scale +/- 0.1
        } else {
            _offsetGoto = 0;
        }
        _offset += _offsetVel;
        if (_offset > 40) _offset = 40;
        if (_offset < -40) _offset = -40;
        _offsetVel += _offsetAcc;
        _offsetVel *= _offsetDamp;
        _offsetAcc = (_offsetGoto - _offset) * _offsetHookes;
    };


    self.drawLabel = function(ctx, line, r) {
        let fontsize = self.nodeFontSize;
        if(self.nodeFontSize == 'auto') {
            fontsize = 40;
        }
        fontsize = parseInt(fontsize)
        ctx.font = `${self.nodeItalic} ${self.nodeBold} ${fontsize}px ${self.nodeFontSelection}`;
        ctx.textAlign = 'center';
        ctx.textBaseline = 'middle';
        ctx.fillStyle = '#000';
        let { width } = ctx.measureText(line);


        if(self.nodeFontSize == 'auto') {
            while (width > r * 2 - 30) {
                fontsize -= 1;
                ctx.font = `${self.nodeItalic} ${self.nodeBold} ${fontsize}px ${self.nodeFontSelection}`;
                width = ctx.measureText(line).width;
            }
        }
        ctx.fillStyle = 'rgba(100%,100%,100%,.15)';
        ctx.fillStyle = '#000';

        ctx.fillText(line, 0, 0);
        if(self.nodeUnderline == 'Underline') {
            drawUnderline(ctx,line);
        }
    }

    // Draw
    let _circleRadius = 0;
    self.draw = function (ctx) {
        if(loopy.pause && !self.wasPaused) {
            // making a copy of the timeout id array
            self.timeouts = self.timeouts.filter((timeout) => {
                let currentTime = new Date().getTime();
                // finding time remaining 
                let returnValue = timeout.time - (currentTime - timeout.startedTime);
                // return true if time remaining
                return returnValue > 0;
            });
            // pause every timeout and checks for time remaining and remove from timeouts array if less than 0
            for(let timeout of self.timeouts){
                timeout.pause();
            }
            // keep from running more than once
            self.wasPaused = true;
        } else if(!loopy.pause && self.wasPaused){
            // unpause every timeout within the timeoutID array
            for(let timeout of self.timeouts){
                timeout.run();
            }
            // keep from running more than once
            self.wasPaused = false;
        }


        // if the node is named autoplay, it will automatically send a signal on play then die
        if (self.loopy.mode === Loopy.MODE_PLAY && self.label === 'autoplay') return;

        // Retina
        const x = self.x * 2;
        const y = self.y * 2;
        const r = self.radius * 2;
        const color = Node.COLORS[self.hue];

        
        // Translate!
        ctx.save();
        ctx.translate(x, y + _offset);

        // DRAW HIGHLIGHT???
        if (self.loopy.sidebar.currentPage.target === self && (self.loopy.mode != Loopy.MODE_PLAY)) {
            ctx.beginPath();
            ctx.arc(0, 0, r + 40, 0, Math.TAU, false);
            ctx.fillStyle = HIGHLIGHT_COLOR;
            ctx.fill();
        }

        // White-gray bubble with colored border
        if (self.foreignColor) {
            ctx.beginPath();
            ctx.arc(0, 0, r + 8, 0, Math.TAU, false);
            ctx.fillStyle = '#fff';
            ctx.fill();
            ctx.lineWidth = 6;
            ctx.strokeStyle = color;
            ctx.stroke();
        }
        ctx.beginPath();
        ctx.arc(0, 0, r - 2, 0, Math.TAU, false);
        ctx.fillStyle = '#fff';
        ctx.fill();
        ctx.lineWidth = 6;
        ctx.strokeStyle = color;
        ctx.stroke();

        
        // INFINITE RANGE FOR RADIUS
        // linear from 0 to 1, asymptotic otherwise.
        let _value;
        if (self.value >= 0 && self.value <= 1) {
            // (0,1) -> (0.1, 0.9)
            _value = 0.1 + 0.8 * self.value;
        } else {
            if (self.value < 0) {
                // asymptotically approach 0, starting at 0.1
                _value = (1 / (Math.abs(self.value) + 1)) * 0.1;
            }
            if (self.value > 1) {
                // asymptotically approach 1, starting at 0.9
                _value = 1 - (1 / self.value) * 0.1;
            }
        }

        // Colored bubble
        ctx.beginPath();
        const _circleRadiusGoto = r * _value; // radius
        _circleRadius = _circleRadius * 0.8 + _circleRadiusGoto * 0.2;
        ctx.arc(0, 0, _circleRadius, 0, Math.TAU, false);
        ctx.fillStyle = color;
        ctx.fill();
        
        let fontsize = self.nodeFontSize;
        if(fontsize == 'auto') {
            fontsize = 40;
        }
        const lines = self.breakText();
        if(lines.length <= 1) {
            self.drawLabel(ctx, self.label, r);
        }
        else {
            const numLines = Math.min(MAX_LINES, lines.length); 
            ctx.translate(0, -(fontsize * numLines) / 3);
            for (let i = 0; i <  numLines; i++) {
                self.drawLabel(ctx, lines[i], r);
                ctx.translate(0, fontsize);
            }
        }

        if (!readOnlyRules() && !loopy.pause) {
            // Controls!
            ctx.globalAlpha = _controlsAlpha;
            ctx.strokeStyle = 'rgba(102, 102, 102)';
            // top arrow
            let arrowHead = new Image();
            arrowHead.src = "css/icons/up-arrow-caret.png";
            ctx.drawImage(arrowHead, -42, -90);
        }

        // draw load balance highlight
        if (self.nodeRatioIsSelected && self.nodeRatioHighlight != "" && self.loopy.mode != Loopy.MODE_PLAY && self.loopy.sidebar.currentPage.target === self) {

            const lines = self.breakText();
            const fontsize = self.nodeFontSize;
            const numLines = Math.min(MAX_LINES, lines.length); 

            let y = 0;
            if (lines.length <= 1) {
                y = (self.nodeRatioHighlight.y - self.y) * 2;
            }
            // if the node has multiple lines of text, adjust the y
            else {
                y = -((fontsize * numLines) / 3) * 2;

                const difference = (self.nodeRatioHighlight.y - self.y) * 2;
                y += difference;
            }

            let x = (self.nodeRatioHighlight.x - self.x) * 2;
   
            ctx.beginPath();
            ctx.arc(x, y, r + 19, 0, Math.TAU);
            ctx.lineWidth = 35;
            ctx.strokeStyle = LOAD_BALANCE_HIGHLIGHT;
            ctx.stroke();
        }

        // Restore
        ctx.restore();
    };

    self.bottleneckStatus = function(ctx) {
        const wip = self.wip;
        const queueLength = self.overCapacity.length;
        // gets percentage of total signals against capacity
        const status = (wip + queueLength) / self.size * 100;

        const INDICATOR_YELLOW = {
            color: '#fac710',
            strokeColor: '#fac710',
            lineWidth: 1
         };
         
         const INDICATOR_RED_LOW = {
            color: '#f24726',
            strokeColor: '#f24726',
            lineWidth: 1
         }
         const INDICATOR_RED_MEDIUM = {
            color: '#bf2507',
            strokeColor: '#847976',
            lineWidth: 5
         };
         
         const INDICATOR_RED_HIGH = {
            color: '#8e1c06',
            strokeColor: 'black',
            lineWidth: 10
         }

        let indicator = null;

        // Red High (default: >=500%)
        if (status >= loopy.indicatorRedHigh) {
            indicator = INDICATOR_RED_HIGH;
            self.bottleneckColor = 'redHighAni';
            self.bottleneckRed = true;
        }
        // Red Medium (default 200%-499.99%)
        else if (status >= loopy.indicatorRedMedium) {
            indicator = INDICATOR_RED_MEDIUM;
            self.bottleneckColor = 'redMediumAni';
            self.bottleneckRed = true;
        }
        // Red Low (default 100%-199.99%)
        else if (status >= loopy.indicatorRedLow) {
            indicator = INDICATOR_RED_LOW;
            self.bottleneckColor = 'redLowAni';
            self.bottleneckRed = true;
        }
        // Yellow (default 70%-99.99%)
        else if (status >= loopy.indicatorYellow) {
            indicator = INDICATOR_YELLOW;
            self.bottleneckColor = 'yellowAni';
        }
        else {
            self.bottleneckColor = 'greenAni';
            self.bottleneckRed = false;
        }

        if (!indicator) return;

        self.drawBottleneck(ctx, indicator.color, indicator.lineWidth, indicator.strokeColor);

    }


    self.drawBottleneck = function(ctx, color, lineWidth, strokeColor){
        const x = self.x * 2 + 255;
        const y = self.y * 2 - 210;
        const radius = 18;
        const startAngle = 0;
        const endAngle = 2 * Math.PI;
        ctx.beginPath();
        ctx.arc(x, y, radius, startAngle, endAngle);
        ctx.fillStyle = color;
        ctx.fill();
        ctx.lineWidth = lineWidth;
        ctx.strokeStyle = strokeColor;
        ctx.stroke();
    }

    self.drawFloatDisplay = function(ctx) {

        const x = self.x * 2 + 100;
        const y = self.y * 2 - 230;

        const width = 180;
        const height = 115;

        const fontsize = 26;
        ctx.font = `normal ${fontsize}px "Roboto", sans-serif`;

        // draw a white box
        ctx.fillStyle = "white";
        ctx.strokeStyle = "black";
        ctx.beginPath();
        ctx.fillRect(x, y, width, height);

        // draws text in the box
        ctx.fillStyle = "black";
        ctx.fillText(`WIP: ${self.wip}`, x+20, y+40);
        ctx.fillText(`In Queue: ${self.overCapacity.length}`, x+20, y+70);
        ctx.fillText(`Capacity: ${self.size}`, x+20, y+100);

        ctx.stroke();

    };



    // Delete node when delete key is pressed and the node is currently selected
    subscribe("key/delete", function(){
        if(self.loopy.sidebar.currentPage.target == self){
        self.kill()
        }
    });
    
    /// ///////////////////////////////////
    // KILL NODE /////////////////////////
    /// ///////////////////////////////////

    self.kill = function () {

        self.unsubscribeAll();

        // Remove from parent!
        whiteboard.removeNode(self);

        // Killed!
        publish('kill', [self]);
    };

    self.unsubscribeAll = function () {
        // Kill Listeners!
        unsubscribe('mousemove', _listenerMouseMove);
        unsubscribe('mousedown', _listenerMouseDown);
        unsubscribe('mouseup', _listenerMouseUp);
        unsubscribe('whiteboard/reset', _listenerReset);
    };
    

    /// ///////////////////////////////////
    // HELPER METHODS ////////////////////
    /// ///////////////////////////////////

    self.isPointInNode = function (x, y, buffer) {
        buffer = buffer || 0;
        return _isPointInCircle(x, y, self.x, self.y, self.radius + buffer);
    };

    self.getBoundingBox = function () {
        return {
            left: self.x - self.radius,
            top: self.y - self.radius,
            right: self.x + self.radius,
            bottom: self.y + self.radius,
        };
    };
}

function radialLine(ctx, baseAngle, baseR, size, rx, ry) {
    ctx.lineTo(Math.cos(baseAngle + rx * size) * baseR * (1 + ry * size), Math.sin(baseAngle + rx * size) * baseR * (1 + ry * size));
}
function radialMove(ctx, baseAngle, baseR, size, rx, ry) {
    ctx.moveTo(Math.cos(baseAngle + rx * size) * baseR * (1 + ry * size), Math.sin(baseAngle + rx * size) * baseR * (1 + ry * size));
}



// Exports for testing
exports.Node = Node;